### ISSUE TITLE
Page-level routing

### ISSUE THREAD

**Issue by thewilkybarkid** [libero/publisher-micro-frontend-experiment#2]
>   The homepage will have links to article pages, but how does it know they exist/what the path is? Feels like the same hypermedia approach would solve this, so an article-page service could also expose an API with entries like:
> 
>   ```json
>   {
>     "@context": "http://schema.org/",
>     "id": "http://example.com/articles/abcde",
>     "type": "ItemPage",
>     "mainEntity": "http://article-store.example.com/some/path/to/12345"
>   }
>   ```
>   
>   So a hypermedia knows to link to `http://example.com/articles/abcde` on a teaser for article `http://article-store.example.com/some/path/to/12345` by doing a lookup operation.
> 
>   This would allow turning off/on of things like subject pages, article type pages etc by running (or not) the relevant page service.
>   
>   Also means it's easy to customise what routes are (e.g. maybe you want to use a DOI in the path, or some other local identifier).
>   
>   This is another layer of complexity though, and is probably a step too far...

**Comment by thewilkybarkid** [comment]
Discovery at this least has two approaches:

1. Embed Hydra details in the HTML
2. Have a separate API

The former is preferable.

I've had a play, and seems possible to do, but requires quite a bit of effort and work on the tooling (Alcaeus is geared towards JSON-LD at the moment).

That said, not sure it's worth it. There's little if anything else to be gained.

So, for now at least, it's probably easier and far simpler to used shared URI templates based on RDF types.

For example, configuration could look like:

```yaml
http://schema.org/ScholarlyArticle: /articles/{doi}
```

So something with the `rdf:type` of `schema:ScholarlyArticle` will have a path based on its DOI.

As to _what_ a DOI is, we'd recognise certain patterns, such as:

```
{
  "@context": "http://schema.org/",
  "type": "ScholarlyArticle",
  "identifier": {
    "type": "PropertyValue",
    "propertyID": "DOI",
    "value": "10.1000/182"
  }
}
```

```
{
  "@context": "http://schema.org/",
  "type": "ScholarlyArticle",
  "identifier": "doi:10.1000/182"
}
```

(In the first, feels like the `schema:propertyID` should be an IRI rather than a literal...)

This is probably good enough for now.

But, in the future, when someone needs custom mappings, eg for:

```yaml
http://schema.org/BlogPosting: /blog/{internal-id}/{slug}
```

A format like

```yaml
mappings:
  doi:
    - type: https://schema.org/identifier
      https://schema/org/propertyID: DOI
    - type: https://schema.org/identifier
      schema: doi
  internal-id:
    - type: https://schema.org/identifier
      https://schema/org/propertyID: internal-id
  slug:
    - type: https://schema.org/identifier
      https://schema/org/propertyID: slug

paths:
  http://schema.org/ScholarlyArticle: /articles/{doi}
  http://schema.org/BlogPosting: /blog/{internal-id}/{slug}
```

could be used. (This is getting similar to [`hydra:IriTemplate`](https://www.hydraecosystem.org/IriTemplate).)
